
`Numpy : Numerical Python `



In [1]:
import numpy as np

In [2]:
n1d=np.array([1,2,3,4,5],dtype=float)

In [3]:
n1d+2


array([3., 4., 5., 6., 7.])

In [4]:
type(n1d)

numpy.ndarray

In [5]:
n1d.max()

np.float64(5.0)

In [6]:
n1d.ndim # dimension

1

In [7]:
n1d.shape  # no of rows and columns

(5,)

In [8]:
lst=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
n2d=np.array(lst)
type(n2d)
n2d.ndim
n2d.shape

(3, 5)

In [9]:
n2d+4

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
n1d.size # no of elements

5

In [11]:
n2d.size

15

In [12]:
n1d.dtype # data type

dtype('float64')

In [13]:
np.arange(1,7)   # range of numbers: start ,end,step

array([1, 2, 3, 4, 5, 6])

In [14]:
n1=np.arange(1,18,2).reshape(3,3) # 2 rows and 3 columns
n2=np.arange(1,18,2).reshape(3,3)
n3=np.array([n1,n2])
n3.ndim

3

In [15]:
n1=np.arange(1,13).reshape(2,2,3)
n2=np.arange(1,13).reshape(2,2,3)
n3=np.array([n1,n2])
n3.ndim

4

In [16]:
# import matplotlib.pyplot as plt
# x=plt.imread("D:\PROJECTS\project_au\copy.jpg")

In [17]:
# x1=x[:,:,0]
# plt.imshow(x1)

In [18]:
# x2=np.rot90(x)
# plt.imshow(x2)

In [19]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.random.seed(3)  # to get same random numbers
np.random.randint(1,10,(2,3))

array([[9, 4, 9],
       [9, 1, 6]], dtype=int32)

In [22]:
n1d[2]

np.float64(3.0)

In [23]:
n2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
n2d[0:1,0:3] # [rs:re:size,cs:ce:size]

array([[1, 2, 3]])

In [25]:
n2d[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [26]:
n2d[0:3:2,0:3:2]=0
n2d

array([[ 0,  2,  0,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0, 12,  0, 14, 15]])

In [27]:
n2d[0:3,[0,2,3]]  # using column index

array([[ 0,  0,  4],
       [ 6,  8,  9],
       [ 0,  0, 14]])

In [28]:
n2d[[0,1],0:3] # using row index

array([[0, 2, 0],
       [6, 7, 8]])

In [29]:
n2d[2,1]

np.int64(12)

In [30]:
n2[0,0:2,1:3]   # bs:be:step,rs:re:step,cs:ce:step

array([[2, 3],
       [5, 6]])