
`Numpy : Numerical Python `



In [1]:
import numpy as np

In [2]:
n1d=np.array([1,2,3,4,5],dtype=float)

In [3]:
n1d+2


array([3., 4., 5., 6., 7.])

In [4]:
type(n1d)

numpy.ndarray

In [5]:
n1d.max()

np.float64(5.0)

In [6]:
n1d.ndim # dimension

1

In [7]:
n1d.shape  # no of rows and columns

(5,)

In [8]:
lst=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
n2d=np.array(lst)
type(n2d)
n2d.ndim
n2d.shape

(3, 5)

In [9]:
n2d+4

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
n1d.size # no of elements

5

In [11]:
n2d.size

15

In [12]:
n1d.dtype # data type

dtype('float64')

In [13]:
np.arange(1,7)   # range of numbers: start ,end,step

array([1, 2, 3, 4, 5, 6])

In [14]:
n1=np.arange(1,18,2).reshape(3,3) # 2 rows and 3 columns
n2=np.arange(1,18,2).reshape(3,3)
n3=np.array([n1,n2])
n3.ndim

3

In [15]:
n1=np.arange(1,13).reshape(2,2,3)
n2=np.arange(1,13).reshape(2,2,3)
n3=np.array([n1,n2])
n3.ndim

4

In [16]:
# import matplotlib.pyplot as plt
# x=plt.imread("D:\PROJECTS\project_au\copy.jpg")

In [17]:
# x1=x[:,:,0]
# plt.imshow(x1)

In [18]:
# x2=np.rot90(x)
# plt.imshow(x2)

In [19]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.random.seed(3)  # to get same random numbers
np.random.randint(1,10,(2,3))

array([[9, 4, 9],
       [9, 1, 6]], dtype=int32)

In [22]:
n1d[2]

np.float64(3.0)

In [23]:
n2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Indexing , Slicing and Fancy Slicing



In [24]:
n2d[0:1,0:3] # [rs:re:size,cs:ce:size]

array([[1, 2, 3]])

In [25]:
n2d[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [26]:
n2d[0:3:2,0:3:2]=0
n2d

array([[ 0,  2,  0,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0, 12,  0, 14, 15]])

In [27]:
n2d[0:3,[0,2,3]]  # using column index

array([[ 0,  0,  4],
       [ 6,  8,  9],
       [ 0,  0, 14]])

In [28]:
n2d[[0,1],0:3] # using row index

array([[0, 2, 0],
       [6, 7, 8]])

In [29]:
n2d[2,1]

np.int64(12)

In [30]:
n2[0,0:2,1:3]   # bs:be:step,rs:re:step,cs:ce:step

array([[2, 3],
       [5, 6]])

### Boolean Masking


In [31]:
n1=np.arange(2,20)

In [32]:
condition=n1>7
n1[condition]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
n1[(n1>7) & (n1<15)]

array([ 8,  9, 10, 11, 12, 13, 14])

In [34]:
n1[(n1>7) | (n1<15)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [35]:
friuts=np.array(["apple","banana","cherry","grapes"])
price=np.array([20,30,5,4])


In [36]:
friuts[price<20]

array(['cherry', 'grapes'], dtype='<U6')

In [37]:
n1=np.arange(15,20)
np.where(n1%2==0,"even","odd")

array(['odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

### Vectorization

In [38]:
n1=np.array([9,8,9,10])
n2=np.array([10,11,12,13])
n1*n2

array([ 90,  88, 108, 130])

### Broadcasting


In [39]:
n1=np.array([1,2])
n2=np.arange(1,5).reshape(2,2)
n1+n2

array([[2, 4],
       [4, 6]])

### Linear Equation

In [40]:
A = np.asarray([[30, -1],               
                [50, -1]])          # asarray = array

Inv_A = np.linalg.inv(A)  # linalg = linear algebra
print(Inv_A)
    

[[-0.05  0.05]
 [-2.5   1.5 ]]


In [41]:
B=np.asarray([-1000,-100])

In [42]:
X=np.dot(Inv_A,B)
X

array([  45., 2350.])

In [46]:
n1=np.arange(1,10).reshape(3,3)
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
n1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
n1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* axis=0 → operation goes down, result per column
* axis=1 → operation goes across, result per row

In [51]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
n1.sum(axis=0) # row sum

array([12, 15, 18])

In [50]:
n1.sum(axis=1) # column sum

array([ 6, 15, 24])

### Stacking

In [52]:
n1=np.arange(1,3)
n2=np.arange(3,5)

In [53]:
np.hstack((n1,n2))

array([1, 2, 3, 4])

In [54]:
np.vstack((n1,n2))

array([[1, 2],
       [3, 4]])

In [55]:
np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4])

In [58]:
np.concatenate((n1.reshape(-1,1),n2.reshape(-1,1)),axis=1)

array([[1, 3],
       [2, 4]])